#!/bin/bash
# 
#	 Tech 'Em Studios 
#	 Chrome Book Install Script
#


echo "Clear screen" 
clear
sleep 2

# Create Students directory
echo "Creating ~/Students directory"
mkdir ~/Students
sleep 1

# Set Time Zone
echo "Setting up timezone"
sleep 2
sudo rm /etc/localtime
sudo ln -s /usr/share/zoneinfo/US/Eastern /etc/localtime

# Turn on PalmDetect 
echo "Adding the PalmDetect technology to make you life not crappy and miserable"
synclient PalmDetect=1
sleep 5

# Create local .xinitrc
echo '#CUSTOM MAGIC' > ~/.xinitrc
sleep 2

# Turn off touchpad while typing
echo "Turning off the touchpad while you type"
echo 'exec syndaemon -K -i 0.5 -R -d' >> ~/.xinitrc
sleep 5

# Add two finger right click
#echo "Enabling Two Finger Tap Right Click"
#sed -i "$a synclient tapbutton2=3" >> ~/.xinitrc
#sleep 5
# Set custom background

echo "Changing desktop background"
xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitoreDP-0/workspace0/last-image --set /home/techemstudent/techem_install/bg.png

# Disable desktop icons to remove clutter
# Encourage students to create folders in ~/Students
echo "Disabling desktop icon..."
xfconf-query -c xfce4-desktop -np '/desktop-icons/style' -t 'int' -s '0';

# Re-enable desktop icons
# xfconf-query -c xfce4-desktop -np '/desktop-icons/style' -t 'int' -s '2';

# Remove bottom panel
echo "Remove Old Panels"
#xfconf-query --channel xfce4-panel --property /panels/panel-0 --reset --recursive
xfconf-query --channel xfce4-panel --property /panels/panel-2 --reset --recursive
xfce4-panel -r &

# Installing Python, and extras
echo "Installing everything Python!"
sudo apt-get --assume-yes install python-matplotlib
sudo apt-get --assume-yes install idle
sudo apt-get --assume-yes install git
sudo apt-get --assume-yes install python-setuptools
sudo apt-get --assume-yes install python-dev
sudo apt-get --assume-yes install build-essential
easy_install pip
sudo apt-get --assume-yes install git-cola
sudo apt-get --assume-yes install python-numpy
sudo apt-get --assume-yes install python-scipy
sudo apt-get --assume-yes install python-pygame

# Install Firefox
echo "Installing Firefox"
sudo apt-get --assume-yes install firefox

# Remove Netsurf
echo "Remove Netsurf"
sudo apt-get remove netsurf
sudo apt-get remove --auto-remove netsurf
sudo apt-get purge netsurf

# Install Geany
echo "Installing Geany" 
sudo apt-get --assume-yes install geany
sudo apt-get --assume-yes install geany
sudo apt-get --assume-yes install emacs

# Install Arduino
sudo apt-get --assume-yes install arduino arduino-core
sudo usermod -a -G tty techemstudent
sudo usermod -a -G dialout techemstudent  
